post_install(){
  echo "NOTE:"
  echo ===================================
  echo To use foam-extend-git paste the following code into your ~/.bashrc file:
  echo "alias fegit='export FOAM_INST_DIR=/opt/OpenFOAM; source \${FOAM_INST_DIR}/foam-extend-git/etc/bashrc'"
  echo Whenever you want to use foam-extend-git type fegit in your terminal to initialize the environment.
  echo ===================================
}

post_upgrade(){
  post_install
}
